/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ApiErrorResponse from '../Model/ApiErrorResponse';
import InlineResponse2002 from '../Model/InlineResponse2002';
import QueueSettings from '../Model/QueueSettings';

/**
* Event service.
* @module GenericApi/Api/EventApi
* @version 1.0.0
*/
export default class EventApi {

    /**
    * Constructs a new EventApi. 
    * @alias module:GenericApi/Api/EventApi
    * @class
    * @param {module:GenericApi/ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:GenericApi/ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the eventsQueueSettings operation.
     * @callback module:GenericApi/Api/EventApi~eventsQueueSettingsCallback
     * @param {String} error Error message, if any.
     * @param {module:GenericApi/Model/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Настройка доступа к RabbitMQ
     * @param {module:GenericApi/Model/QueueSettings} body Настройки доступа к RabbitMQ
     * @param {module:GenericApi/Api/EventApi~eventsQueueSettingsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:GenericApi/Model/InlineResponse2002}
     */
    eventsQueueSettings(body, callback) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling eventsQueueSettings");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;
      return this.apiClient.callApi(
        '/api/events/queue/settings.json', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
