/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiErrorResponse from './Model/ApiErrorResponse';
import ApiSucessResponseWithId from './Model/ApiSucessResponseWithId';
import InlineObject from './Model/InlineObject';
import InlineObject1 from './Model/InlineObject1';
import InlineObject10 from './Model/InlineObject10';
import InlineObject11 from './Model/InlineObject11';
import InlineObject12 from './Model/InlineObject12';
import InlineObject13 from './Model/InlineObject13';
import InlineObject14 from './Model/InlineObject14';
import InlineObject2 from './Model/InlineObject2';
import InlineObject3 from './Model/InlineObject3';
import InlineObject4 from './Model/InlineObject4';
import InlineObject5 from './Model/InlineObject5';
import InlineObject6 from './Model/InlineObject6';
import InlineObject7 from './Model/InlineObject7';
import InlineObject8 from './Model/InlineObject8';
import InlineObject9 from './Model/InlineObject9';
import InlineResponse200 from './Model/InlineResponse200';
import InlineResponse2001 from './Model/InlineResponse2001';
import InlineResponse20010 from './Model/InlineResponse20010';
import InlineResponse20011 from './Model/InlineResponse20011';
import InlineResponse20012 from './Model/InlineResponse20012';
import InlineResponse20013 from './Model/InlineResponse20013';
import InlineResponse2002 from './Model/InlineResponse2002';
import InlineResponse2003 from './Model/InlineResponse2003';
import InlineResponse2004 from './Model/InlineResponse2004';
import InlineResponse2005 from './Model/InlineResponse2005';
import InlineResponse2006 from './Model/InlineResponse2006';
import InlineResponse2007 from './Model/InlineResponse2007';
import InlineResponse2008 from './Model/InlineResponse2008';
import InlineResponse2009 from './Model/InlineResponse2009';
import Instance from './Model/Instance';
import InstanceConfig from './Model/InstanceConfig';
import Inventory from './Model/Inventory';
import InventoryItem from './Model/InventoryItem';
import InventoryItemFull from './Model/InventoryItemFull';
import InventoryOptions from './Model/InventoryOptions';
import LastValue from './Model/LastValue';
import Metric from './Model/Metric';
import MetricValue from './Model/MetricValue';
import ModelObject from './Model/ModelObject';
import ObjectResponse from './Model/ObjectResponse';
import PaginationRequest from './Model/PaginationRequest';
import PaginationResponce from './Model/PaginationResponce';
import QueueSettings from './Model/QueueSettings';
import QueueSettingsExchange from './Model/QueueSettingsExchange';
import QueueSettingsQueue from './Model/QueueSettingsQueue';
import Trigger from './Model/Trigger';
import EventApi from './Api/EventApi';
import InstanceApi from './Api/InstanceApi';
import InventoryApi from './Api/InventoryApi';
import MetricApi from './Api/MetricApi';
import ObjectApi from './Api/ObjectApi';
import TriggerApi from './Api/TriggerApi';


/**
* Клиентская библиотека для работы с Generic API.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GenericApi = require('GenericApi/index'); // See note below*.
* var xxxSvc = new GenericApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GenericApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['GenericApi/index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GenericApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GenericApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module GenericApi/index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:GenericApi/ApiClient}
     */
    ApiClient,

    /**
     * The ApiErrorResponse model constructor.
     * @property {module:GenericApi/Model/ApiErrorResponse}
     */
    ApiErrorResponse,

    /**
     * The ApiSucessResponseWithId model constructor.
     * @property {module:GenericApi/Model/ApiSucessResponseWithId}
     */
    ApiSucessResponseWithId,

    /**
     * The InlineObject model constructor.
     * @property {module:GenericApi/Model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:GenericApi/Model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject10 model constructor.
     * @property {module:GenericApi/Model/InlineObject10}
     */
    InlineObject10,

    /**
     * The InlineObject11 model constructor.
     * @property {module:GenericApi/Model/InlineObject11}
     */
    InlineObject11,

    /**
     * The InlineObject12 model constructor.
     * @property {module:GenericApi/Model/InlineObject12}
     */
    InlineObject12,

    /**
     * The InlineObject13 model constructor.
     * @property {module:GenericApi/Model/InlineObject13}
     */
    InlineObject13,

    /**
     * The InlineObject14 model constructor.
     * @property {module:GenericApi/Model/InlineObject14}
     */
    InlineObject14,

    /**
     * The InlineObject2 model constructor.
     * @property {module:GenericApi/Model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:GenericApi/Model/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject4 model constructor.
     * @property {module:GenericApi/Model/InlineObject4}
     */
    InlineObject4,

    /**
     * The InlineObject5 model constructor.
     * @property {module:GenericApi/Model/InlineObject5}
     */
    InlineObject5,

    /**
     * The InlineObject6 model constructor.
     * @property {module:GenericApi/Model/InlineObject6}
     */
    InlineObject6,

    /**
     * The InlineObject7 model constructor.
     * @property {module:GenericApi/Model/InlineObject7}
     */
    InlineObject7,

    /**
     * The InlineObject8 model constructor.
     * @property {module:GenericApi/Model/InlineObject8}
     */
    InlineObject8,

    /**
     * The InlineObject9 model constructor.
     * @property {module:GenericApi/Model/InlineObject9}
     */
    InlineObject9,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:GenericApi/Model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:GenericApi/Model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:GenericApi/Model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse20011 model constructor.
     * @property {module:GenericApi/Model/InlineResponse20011}
     */
    InlineResponse20011,

    /**
     * The InlineResponse20012 model constructor.
     * @property {module:GenericApi/Model/InlineResponse20012}
     */
    InlineResponse20012,

    /**
     * The InlineResponse20013 model constructor.
     * @property {module:GenericApi/Model/InlineResponse20013}
     */
    InlineResponse20013,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:GenericApi/Model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:GenericApi/Model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:GenericApi/Model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:GenericApi/Model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:GenericApi/Model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:GenericApi/Model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:GenericApi/Model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:GenericApi/Model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The Instance model constructor.
     * @property {module:GenericApi/Model/Instance}
     */
    Instance,

    /**
     * The InstanceConfig model constructor.
     * @property {module:GenericApi/Model/InstanceConfig}
     */
    InstanceConfig,

    /**
     * The Inventory model constructor.
     * @property {module:GenericApi/Model/Inventory}
     */
    Inventory,

    /**
     * The InventoryItem model constructor.
     * @property {module:GenericApi/Model/InventoryItem}
     */
    InventoryItem,

    /**
     * The InventoryItemFull model constructor.
     * @property {module:GenericApi/Model/InventoryItemFull}
     */
    InventoryItemFull,

    /**
     * The InventoryOptions model constructor.
     * @property {module:GenericApi/Model/InventoryOptions}
     */
    InventoryOptions,

    /**
     * The LastValue model constructor.
     * @property {module:GenericApi/Model/LastValue}
     */
    LastValue,

    /**
     * The Metric model constructor.
     * @property {module:GenericApi/Model/Metric}
     */
    Metric,

    /**
     * The MetricValue model constructor.
     * @property {module:GenericApi/Model/MetricValue}
     */
    MetricValue,

    /**
     * The ModelObject model constructor.
     * @property {module:GenericApi/Model/ModelObject}
     */
    ModelObject,

    /**
     * The ObjectResponse model constructor.
     * @property {module:GenericApi/Model/ObjectResponse}
     */
    ObjectResponse,

    /**
     * The PaginationRequest model constructor.
     * @property {module:GenericApi/Model/PaginationRequest}
     */
    PaginationRequest,

    /**
     * The PaginationResponce model constructor.
     * @property {module:GenericApi/Model/PaginationResponce}
     */
    PaginationResponce,

    /**
     * The QueueSettings model constructor.
     * @property {module:GenericApi/Model/QueueSettings}
     */
    QueueSettings,

    /**
     * The QueueSettingsExchange model constructor.
     * @property {module:GenericApi/Model/QueueSettingsExchange}
     */
    QueueSettingsExchange,

    /**
     * The QueueSettingsQueue model constructor.
     * @property {module:GenericApi/Model/QueueSettingsQueue}
     */
    QueueSettingsQueue,

    /**
     * The Trigger model constructor.
     * @property {module:GenericApi/Model/Trigger}
     */
    Trigger,

    /**
    * The EventApi service constructor.
    * @property {module:GenericApi/Api/EventApi}
    */
    EventApi,

    /**
    * The InstanceApi service constructor.
    * @property {module:GenericApi/Api/InstanceApi}
    */
    InstanceApi,

    /**
    * The InventoryApi service constructor.
    * @property {module:GenericApi/Api/InventoryApi}
    */
    InventoryApi,

    /**
    * The MetricApi service constructor.
    * @property {module:GenericApi/Api/MetricApi}
    */
    MetricApi,

    /**
    * The ObjectApi service constructor.
    * @property {module:GenericApi/Api/ObjectApi}
    */
    ObjectApi,

    /**
    * The TriggerApi service constructor.
    * @property {module:GenericApi/Api/TriggerApi}
    */
    TriggerApi
};
