/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiErrorResponse model module.
 * @module GenericApi/Model/ApiErrorResponse
 * @version 1.0.0
 */
class ApiErrorResponse {
    /**
     * Constructs a new <code>ApiErrorResponse</code>.
     * @alias module:GenericApi/Model/ApiErrorResponse
     */
    constructor() { 
        
        ApiErrorResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/ApiErrorResponse} obj Optional instance to populate.
     * @return {module:GenericApi/Model/ApiErrorResponse} The populated <code>ApiErrorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiErrorResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} success
 */
ApiErrorResponse.prototype['success'] = undefined;

/**
 * Внутренний код ошибки
 * @member {Number} code
 */
ApiErrorResponse.prototype['code'] = undefined;

/**
 * @member {String} message
 */
ApiErrorResponse.prototype['message'] = undefined;






export default ApiErrorResponse;

