/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ApiSucessResponseWithId model module.
 * @module GenericApi/Model/ApiSucessResponseWithId
 * @version 1.0.0
 */
class ApiSucessResponseWithId {
    /**
     * Constructs a new <code>ApiSucessResponseWithId</code>.
     * @alias module:GenericApi/Model/ApiSucessResponseWithId
     */
    constructor() { 
        
        ApiSucessResponseWithId.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ApiSucessResponseWithId</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/ApiSucessResponseWithId} obj Optional instance to populate.
     * @return {module:GenericApi/Model/ApiSucessResponseWithId} The populated <code>ApiSucessResponseWithId</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiSucessResponseWithId();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} success
 */
ApiSucessResponseWithId.prototype['success'] = undefined;

/**
 * @member {Number} id
 */
ApiSucessResponseWithId.prototype['id'] = undefined;






export default ApiSucessResponseWithId;

