/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject11 model module.
 * @module GenericApi/Model/InlineObject11
 * @version 1.0.0
 */
class InlineObject11 {
    /**
     * Constructs a new <code>InlineObject11</code>.
     * @alias module:GenericApi/Model/InlineObject11
     * @param ids {Array.<Number>} 
     * @param fromTs {Number} Дата и время начала период
     * @param toTs {Number} Дата и время конца периода
     */
    constructor(ids, fromTs, toTs) { 
        
        InlineObject11.initialize(this, ids, fromTs, toTs);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, ids, fromTs, toTs) { 
        obj['ids'] = ids;
        obj['from_ts'] = fromTs;
        obj['to_ts'] = toTs;
    }

    /**
     * Constructs a <code>InlineObject11</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/InlineObject11} obj Optional instance to populate.
     * @return {module:GenericApi/Model/InlineObject11} The populated <code>InlineObject11</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject11();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['Number']);
            }
            if (data.hasOwnProperty('from_ts')) {
                obj['from_ts'] = ApiClient.convertToType(data['from_ts'], 'Number');
            }
            if (data.hasOwnProperty('to_ts')) {
                obj['to_ts'] = ApiClient.convertToType(data['to_ts'], 'Number');
            }
            if (data.hasOwnProperty('group_div')) {
                obj['group_div'] = ApiClient.convertToType(data['group_div'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} ids
 */
InlineObject11.prototype['ids'] = undefined;

/**
 * Дата и время начала период
 * @member {Number} from_ts
 */
InlineObject11.prototype['from_ts'] = undefined;

/**
 * Дата и время конца периода
 * @member {Number} to_ts
 */
InlineObject11.prototype['to_ts'] = undefined;

/**
 * Число секунд, для группировки выборки
 * @member {Number} group_div
 */
InlineObject11.prototype['group_div'] = undefined;






export default InlineObject11;

