/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject3 model module.
 * @module GenericApi/Model/InlineObject3
 * @version 1.0.0
 */
class InlineObject3 {
    /**
     * Constructs a new <code>InlineObject3</code>.
     * @alias module:GenericApi/Model/InlineObject3
     * @param id {Number} 
     */
    constructor(id) { 
        
        InlineObject3.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>InlineObject3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/InlineObject3} obj Optional instance to populate.
     * @return {module:GenericApi/Model/InlineObject3} The populated <code>InlineObject3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject3();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('return_inventory')) {
                obj['return_inventory'] = ApiClient.convertToType(data['return_inventory'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
InlineObject3.prototype['id'] = undefined;

/**
 * Флаг, сообщающий коннектору, что надо вернуть все inventory для запрошенного объекта
 * @member {Boolean} return_inventory
 */
InlineObject3.prototype['return_inventory'] = undefined;






export default InlineObject3;

