/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaginationRequest from './PaginationRequest';

/**
 * The InlineObject5 model module.
 * @module GenericApi/Model/InlineObject5
 * @version 1.0.0
 */
class InlineObject5 {
    /**
     * Constructs a new <code>InlineObject5</code>.
     * @alias module:GenericApi/Model/InlineObject5
     * @param instanceCode {String} Уникальный алфавитно-цифровой идентификатор инстанса, которому принадлежит объект
     */
    constructor(instanceCode) { 
        
        InlineObject5.initialize(this, instanceCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, instanceCode) { 
        obj['instance_code'] = instanceCode;
    }

    /**
     * Constructs a <code>InlineObject5</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/InlineObject5} obj Optional instance to populate.
     * @return {module:GenericApi/Model/InlineObject5} The populated <code>InlineObject5</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject5();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['Number']);
            }
            if (data.hasOwnProperty('instance_code')) {
                obj['instance_code'] = ApiClient.convertToType(data['instance_code'], 'String');
            }
            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('return_inventory')) {
                obj['return_inventory'] = ApiClient.convertToType(data['return_inventory'], 'Boolean');
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = PaginationRequest.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} ids
 */
InlineObject5.prototype['ids'] = undefined;

/**
 * Уникальный алфавитно-цифровой идентификатор инстанса, которому принадлежит объект
 * @member {String} instance_code
 */
InlineObject5.prototype['instance_code'] = undefined;

/**
 * @member {Number} parent_id
 */
InlineObject5.prototype['parent_id'] = undefined;

/**
 * @member {String} name
 */
InlineObject5.prototype['name'] = undefined;

/**
 * @member {Boolean} return_inventory
 */
InlineObject5.prototype['return_inventory'] = undefined;

/**
 * @member {module:GenericApi/Model/PaginationRequest} pagination
 */
InlineObject5.prototype['pagination'] = undefined;






export default InlineObject5;

