/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaginationRequest from './PaginationRequest';

/**
 * The InlineObject14 model module.
 * @module GenericApi/Model/InlineObject14
 * @version 1.0.0
 */
class InlineObject14 {
    /**
     * Constructs a new <code>InlineObject14</code>.
     * @alias module:GenericApi/Model/InlineObject14
     */
    constructor() { 
        
        InlineObject14.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject14</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/InlineObject14} obj Optional instance to populate.
     * @return {module:GenericApi/Model/InlineObject14} The populated <code>InlineObject14</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject14();

            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['Number']);
            }
            if (data.hasOwnProperty('object_ids')) {
                obj['object_ids'] = ApiClient.convertToType(data['object_ids'], ['Number']);
            }
            if (data.hasOwnProperty('metric_ids')) {
                obj['metric_ids'] = ApiClient.convertToType(data['metric_ids'], ['Number']);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = PaginationRequest.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} ids
 */
InlineObject14.prototype['ids'] = undefined;

/**
 * @member {Array.<Number>} object_ids
 */
InlineObject14.prototype['object_ids'] = undefined;

/**
 * @member {Array.<Number>} metric_ids
 */
InlineObject14.prototype['metric_ids'] = undefined;

/**
 * @member {module:GenericApi/Model/PaginationRequest} pagination
 */
InlineObject14.prototype['pagination'] = undefined;






export default InlineObject14;

