/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaginationRequest from './PaginationRequest';

/**
 * The InlineObject9 model module.
 * @module GenericApi/Model/InlineObject9
 * @version 1.0.0
 */
class InlineObject9 {
    /**
     * Constructs a new <code>InlineObject9</code>.
     * @alias module:GenericApi/Model/InlineObject9
     * @param instanceCode {String} Уникальный алфавитно-цифровой идентификатор инстанса, которому принадлежит объект
     */
    constructor(instanceCode) { 
        
        InlineObject9.initialize(this, instanceCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, instanceCode) { 
        obj['instance_code'] = instanceCode;
    }

    /**
     * Constructs a <code>InlineObject9</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/InlineObject9} obj Optional instance to populate.
     * @return {module:GenericApi/Model/InlineObject9} The populated <code>InlineObject9</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject9();

            if (data.hasOwnProperty('keys')) {
                obj['keys'] = ApiClient.convertToType(data['keys'], ['String']);
            }
            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['Number']);
            }
            if (data.hasOwnProperty('object_ids')) {
                obj['object_ids'] = ApiClient.convertToType(data['object_ids'], ['Number']);
            }
            if (data.hasOwnProperty('instance_code')) {
                obj['instance_code'] = ApiClient.convertToType(data['instance_code'], 'String');
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = PaginationRequest.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<String>} keys
 */
InlineObject9.prototype['keys'] = undefined;

/**
 * @member {Array.<Number>} ids
 */
InlineObject9.prototype['ids'] = undefined;

/**
 * @member {Array.<Number>} object_ids
 */
InlineObject9.prototype['object_ids'] = undefined;

/**
 * Уникальный алфавитно-цифровой идентификатор инстанса, которому принадлежит объект
 * @member {String} instance_code
 */
InlineObject9.prototype['instance_code'] = undefined;

/**
 * @member {module:GenericApi/Model/PaginationRequest} pagination
 */
InlineObject9.prototype['pagination'] = undefined;






export default InlineObject9;

