/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ObjectResponse from './ObjectResponse';
import PaginationResponce from './PaginationResponce';

/**
 * The InlineResponse2005 model module.
 * @module GenericApi/Model/InlineResponse2005
 * @version 1.0.0
 */
class InlineResponse2005 {
    /**
     * Constructs a new <code>InlineResponse2005</code>.
     * @alias module:GenericApi/Model/InlineResponse2005
     */
    constructor() { 
        
        InlineResponse2005.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2005</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/InlineResponse2005} obj Optional instance to populate.
     * @return {module:GenericApi/Model/InlineResponse2005} The populated <code>InlineResponse2005</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2005();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('objects')) {
                obj['objects'] = ApiClient.convertToType(data['objects'], [ObjectResponse]);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = PaginationResponce.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} success
 */
InlineResponse2005.prototype['success'] = undefined;

/**
 * @member {Array.<module:GenericApi/Model/ObjectResponse>} objects
 */
InlineResponse2005.prototype['objects'] = undefined;

/**
 * @member {module:GenericApi/Model/PaginationResponce} pagination
 */
InlineResponse2005.prototype['pagination'] = undefined;






export default InlineResponse2005;

