/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InventoryItemFull model module.
 * @module GenericApi/Model/InventoryItemFull
 * @version 1.0.0
 */
class InventoryItemFull {
    /**
     * Constructs a new <code>InventoryItemFull</code>.
     * @alias module:GenericApi/Model/InventoryItemFull
     */
    constructor() { 
        
        InventoryItemFull.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InventoryItemFull</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/InventoryItemFull} obj Optional instance to populate.
     * @return {module:GenericApi/Model/InventoryItemFull} The populated <code>InventoryItemFull</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryItemFull();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
            if (data.hasOwnProperty('value_title')) {
                obj['value_title'] = ApiClient.convertToType(data['value_title'], 'String');
            }
            if (data.hasOwnProperty('last_updated_ts')) {
                obj['last_updated_ts'] = ApiClient.convertToType(data['last_updated_ts'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
InventoryItemFull.prototype['key'] = undefined;

/**
 * @member {String} type
 */
InventoryItemFull.prototype['type'] = undefined;

/**
 * @member {String} value
 */
InventoryItemFull.prototype['value'] = undefined;

/**
 * @member {String} value_title
 */
InventoryItemFull.prototype['value_title'] = undefined;

/**
 * @member {Number} last_updated_ts
 */
InventoryItemFull.prototype['last_updated_ts'] = undefined;






export default InventoryItemFull;

