/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryOptions from './InventoryOptions';

/**
 * The Inventory model module.
 * @module GenericApi/Model/Inventory
 * @version 1.0.0
 */
class Inventory {
    /**
     * Constructs a new <code>Inventory</code>.
     * @alias module:GenericApi/Model/Inventory
     */
    constructor() { 
        
        Inventory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Inventory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/Inventory} obj Optional instance to populate.
     * @return {module:GenericApi/Model/Inventory} The populated <code>Inventory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Inventory();

            if (data.hasOwnProperty('instance_code')) {
                obj['instance_code'] = ApiClient.convertToType(data['instance_code'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], [InventoryOptions]);
            }
        }
        return obj;
    }


}

/**
 * Уникальный алфавитно-цифровой идентификатор инстанса, которому принадлежит объект
 * @member {String} instance_code
 */
Inventory.prototype['instance_code'] = undefined;

/**
 * @member {String} key
 */
Inventory.prototype['key'] = undefined;

/**
 * @member {String} type
 */
Inventory.prototype['type'] = undefined;

/**
 * @member {String} name
 */
Inventory.prototype['name'] = undefined;

/**
 * @member {Array.<module:GenericApi/Model/InventoryOptions>} options
 */
Inventory.prototype['options'] = undefined;






export default Inventory;

