/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LastValue model module.
 * @module GenericApi/Model/LastValue
 * @version 1.0.0
 */
class LastValue {
    /**
     * Constructs a new <code>LastValue</code>.
     * @alias module:GenericApi/Model/LastValue
     */
    constructor() { 
        
        LastValue.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LastValue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/LastValue} obj Optional instance to populate.
     * @return {module:GenericApi/Model/LastValue} The populated <code>LastValue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LastValue();

            if (data.hasOwnProperty('metric_id')) {
                obj['metric_id'] = ApiClient.convertToType(data['metric_id'], 'Number');
            }
            if (data.hasOwnProperty('value_string')) {
                obj['value_string'] = ApiClient.convertToType(data['value_string'], 'String');
            }
            if (data.hasOwnProperty('value_number')) {
                obj['value_number'] = ApiClient.convertToType(data['value_number'], 'Number');
            }
            if (data.hasOwnProperty('last_updated_ts')) {
                obj['last_updated_ts'] = ApiClient.convertToType(data['last_updated_ts'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} metric_id
 */
LastValue.prototype['metric_id'] = undefined;

/**
 * Значение метрики такое, каким оно было получено из источника
 * @member {String} value_string
 */
LastValue.prototype['value_string'] = undefined;

/**
 * Значение, полученное из источника и приведенное к типу float
 * @member {Number} value_number
 */
LastValue.prototype['value_number'] = undefined;

/**
 * @member {Number} last_updated_ts
 */
LastValue.prototype['last_updated_ts'] = undefined;






export default LastValue;

