/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Metric model module.
 * @module GenericApi/Model/Metric
 * @version 1.0.0
 */
class Metric {
    /**
     * Constructs a new <code>Metric</code>.
     * @alias module:GenericApi/Model/Metric
     */
    constructor() { 
        
        Metric.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Metric</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/Metric} obj Optional instance to populate.
     * @return {module:GenericApi/Model/Metric} The populated <code>Metric</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Metric();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('object_id')) {
                obj['object_id'] = ApiClient.convertToType(data['object_id'], 'Number');
            }
            if (data.hasOwnProperty('instance_code')) {
                obj['instance_code'] = ApiClient.convertToType(data['instance_code'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
            if (data.hasOwnProperty('last_updated_ts')) {
                obj['last_updated_ts'] = ApiClient.convertToType(data['last_updated_ts'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Metric.prototype['id'] = undefined;

/**
 * @member {Number} object_id
 */
Metric.prototype['object_id'] = undefined;

/**
 * Уникальный алфавитно-цифровой идентификатор инстанса, которому принадлежит объект
 * @member {String} instance_code
 */
Metric.prototype['instance_code'] = undefined;

/**
 * @member {String} key
 */
Metric.prototype['key'] = undefined;

/**
 * @member {String} name
 */
Metric.prototype['name'] = undefined;

/**
 * @member {String} unit
 */
Metric.prototype['unit'] = undefined;

/**
 * @member {Number} last_updated_ts
 */
Metric.prototype['last_updated_ts'] = undefined;






export default Metric;

