/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryItem from './InventoryItem';

/**
 * The ModelObject model module.
 * @module GenericApi/Model/ModelObject
 * @version 1.0.0
 */
class ModelObject {
    /**
     * Constructs a new <code>ModelObject</code>.
     * @alias module:GenericApi/Model/ModelObject
     * @param id {Number} 
     * @param name {String} 
     */
    constructor(id, name) { 
        
        ModelObject.initialize(this, id, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, name) { 
        obj['id'] = id;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>ModelObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/ModelObject} obj Optional instance to populate.
     * @return {module:GenericApi/Model/ModelObject} The populated <code>ModelObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelObject();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('instance_code')) {
                obj['instance_code'] = ApiClient.convertToType(data['instance_code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('parent_id')) {
                obj['parent_id'] = ApiClient.convertToType(data['parent_id'], 'Number');
            }
            if (data.hasOwnProperty('inventory')) {
                obj['inventory'] = ApiClient.convertToType(data['inventory'], [InventoryItem]);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ModelObject.prototype['id'] = undefined;

/**
 * Уникальный алфавитно-цифровой идентификатор инстанса, которому принадлежит объект
 * @member {String} instance_code
 */
ModelObject.prototype['instance_code'] = undefined;

/**
 * @member {String} name
 */
ModelObject.prototype['name'] = undefined;

/**
 * @member {Number} parent_id
 */
ModelObject.prototype['parent_id'] = undefined;

/**
 * @member {Array.<module:GenericApi/Model/InventoryItem>} inventory
 */
ModelObject.prototype['inventory'] = undefined;






export default ModelObject;

