/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PaginationRequest model module.
 * @module GenericApi/Model/PaginationRequest
 * @version 1.0.0
 */
class PaginationRequest {
    /**
     * Constructs a new <code>PaginationRequest</code>.
     * @alias module:GenericApi/Model/PaginationRequest
     */
    constructor() { 
        
        PaginationRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PaginationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/PaginationRequest} obj Optional instance to populate.
     * @return {module:GenericApi/Model/PaginationRequest} The populated <code>PaginationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaginationRequest();

            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Количество возвращаемых данных за один раз
 * @member {Number} limit
 */
PaginationRequest.prototype['limit'] = undefined;

/**
 * Смещение, начиная с которого надо возвращать данные
 * @member {Number} start
 */
PaginationRequest.prototype['start'] = undefined;






export default PaginationRequest;

