/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueueSettingsExchange model module.
 * @module GenericApi/Model/QueueSettingsExchange
 * @version 1.0.0
 */
class QueueSettingsExchange {
    /**
     * Constructs a new <code>QueueSettingsExchange</code>.
     * @alias module:GenericApi/Model/QueueSettingsExchange
     * @param name {String} 
     * @param type {String} 
     */
    constructor(name, type) { 
        
        QueueSettingsExchange.initialize(this, name, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, type) { 
        obj['name'] = name;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>QueueSettingsExchange</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/QueueSettingsExchange} obj Optional instance to populate.
     * @return {module:GenericApi/Model/QueueSettingsExchange} The populated <code>QueueSettingsExchange</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueueSettingsExchange();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
QueueSettingsExchange.prototype['name'] = undefined;

/**
 * @member {String} type
 */
QueueSettingsExchange.prototype['type'] = undefined;






export default QueueSettingsExchange;

