/**
 * Generic API
 * Стандартизованное API коннектора, предназначенного для интеграции с внешним источником данных. Общая спецификация [тут](https://co-ms.atlassian.net/wiki/spaces/NC/pages/85852315/Generic+API)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QueueSettingsQueue model module.
 * @module GenericApi/Model/QueueSettingsQueue
 * @version 1.0.0
 */
class QueueSettingsQueue {
    /**
     * Constructs a new <code>QueueSettingsQueue</code>.
     * @alias module:GenericApi/Model/QueueSettingsQueue
     * @param name {String} 
     * @param routingKey {String} 
     */
    constructor(name, routingKey) { 
        
        QueueSettingsQueue.initialize(this, name, routingKey);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, routingKey) { 
        obj['name'] = name;
        obj['routing_key'] = routingKey;
    }

    /**
     * Constructs a <code>QueueSettingsQueue</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:GenericApi/Model/QueueSettingsQueue} obj Optional instance to populate.
     * @return {module:GenericApi/Model/QueueSettingsQueue} The populated <code>QueueSettingsQueue</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QueueSettingsQueue();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('routing_key')) {
                obj['routing_key'] = ApiClient.convertToType(data['routing_key'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
QueueSettingsQueue.prototype['name'] = undefined;

/**
 * @member {String} routing_key
 */
QueueSettingsQueue.prototype['routing_key'] = undefined;






export default QueueSettingsQueue;

